/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2019 Matthias Brugger
 * Author: Matthias Brugger <matthias.bgg@kernel.org>
 */

#ifndef _DT_BINDINGS_CLK_MT6589_H
#define _DT_BINDINGS_CLK_MT6589_H

/* TOPCKGEN */

#define CLK_TOP_DSI0_LNTC_DSICLK	1
#define CLK_TOP_HDMITX_CLKDIG_CTS	2
#define CLK_TOP_CLKPH_MCK		3
#define CLK_TOP_CPUM_TCK_IN		4
#define CLK_TOP_MAINPLL_806M		5
#define CLK_TOP_MAINPLL_537P3M		6
#define CLK_TOP_MAINPLL_322P4M		7
#define CLK_TOP_MAINPLL_230P3M		8
#define CLK_TOP_UNIVPLL_624M		9
#define CLK_TOP_UNIVPLL_416M		10
#define CLK_TOP_UNIVPLL_249P6M		11
#define CLK_TOP_UNIVPLL_178P3M		12
#define CLK_TOP_UNIVPLL_48M		13
#define CLK_TOP_MMPLL_D2		14
#define CLK_TOP_MMPLL_D3		15
#define CLK_TOP_MMPLL_D5		16
#define CLK_TOP_MMPLL_D7		17
#define CLK_TOP_MMPLL_D4		18
#define CLK_TOP_MMPLL_D6		19
#define CLK_TOP_SYSPLL_D2		20
#define CLK_TOP_SYSPLL_D4		21
#define CLK_TOP_SYSPLL_D6		22
#define CLK_TOP_SYSPLL_D8		23
#define CLK_TOP_SYSPLL_D10		24
#define CLK_TOP_SYSPLL_D12		25
#define CLK_TOP_SYSPLL_D16		26
#define CLK_TOP_SYSPLL_D24		27
#define CLK_TOP_SYSPLL_D3		28
#define CLK_TOP_SYSPLL_D5		29
#define CLK_TOP_SYSPLL_D3P5		30
#define CLK_TOP_UNIVPLL1_D2		31
#define CLK_TOP_UNIVPLL1_D4		32
#define CLK_TOP_UNIVPLL1_D6		33
#define CLK_TOP_UNIVPLL1_D8		34
#define CLK_TOP_UNIVPLL1_D10		35
#define CLK_TOP_UNIVPLL2_D2		36
#define CLK_TOP_UNIVPLL2_D4		37
#define CLK_TOP_UNIVPLL2_D6		38
#define CLK_TOP_UNIVPLL2_D8		39
#define CLK_TOP_UNIVPLL_D5		40
#define CLK_TOP_UNIVPLL_D7		41
#define CLK_TOP_UNIVPLL_D10		42
#define CLK_TOP_UNIVPLL_D26		43
#define CLK_TOP_LVDSPLL_D2		44
#define CLK_TOP_LVDSPLL_D4		45
#define CLK_TOP_LVDSPLL_D8		46
#define CLK_TOP_MEMPLL_MCK_D4		47
#define CLK_TOP_AXI_SEL			48
#define CLK_TOP_SMI_SEL			49
#define CLK_TOP_MFG_SEL			50
#define CLK_TOP_IRDA_SEL		51
#define CLK_TOP_CAM_SEL			52
#define CLK_TOP_AUD_INTBUS_SEL		53
#define CLK_TOP_JPG_SEL			54
#define CLK_TOP_DISP_SEL		55
#define CLK_TOP_MSDC30_1_SEL		56
#define CLK_TOP_MSDC30_2_SEL		57
#define CLK_TOP_MSDC30_3_SEL		58
#define CLK_TOP_MSDC30_4_SEL		59
#define CLK_TOP_USB20_SEL		60
#define CLK_TOP_HYD_SEL			61
#define CLK_TOP_VENC_SEL		62
#define CLK_TOP_SPI_SEL			63
#define CLK_TOP_UART_SEL		64
#define CLK_TOP_DPI_SEL			65
#define CLK_TOP_MIPI_SEL		66
#define CLK_TOP_MEM_SEL			67
#define CLK_TOP_CAMTG_SEL		68
#define CLK_TOP_AUDIO_SEL		69
#define CLK_TOP_FIX_SEL			70
#define CLK_TOP_VDEC_SEL		71
#define CLK_TOP_DDRPHYCFG_SEL		72
#define CLK_TOP_DPILVDS_SEL		73
#define CLK_TOP_PMICSPI_SEL		74
#define CLK_TOP_MSDC30_0_SEL		75
#define CLK_TOP_SMI_MFG_AS_SEL		76
#define CLK_TOP_NR_CLK			77

#define CLK_TOP_PMICSPI_CG		1
#define CLK_TOP_NR_PMIC			2

/* CLK_APMIXED_SYS */

#define CLK_APMIXED_ARMPLL		1
#define CLK_APMIXED_MAINPLL		2
#define CLK_APMIXED_UNIVPLL		3
#define CLK_APMIXED_MMPLL		4
#define CLK_APMIXED_ISPPLL		5
#define CLK_APMIXED_MSDCPLL		6
#define CLK_APMIXED_TVDPLL		7
#define CLK_APMIXED_LVDSPLL		8

/* CLK_INFRA_SYS */

#define CLK_INFRA_PMIC_WRAP_CK	1
#define CLK_INFRA_PMICSPI_CK	2
#define CLK_INFRA_CCIF1_AP_CTRL	3
#define CLK_INFRA_CCIF0_AP_CTRL	4
#define CLK_INFRA_KP_CK		5
#define CLK_INFRA_CPUM_CK		6
#define CLK_INFRA_M4U_CK		7
#define CLK_INFRA_MFGAXI_CK		8
#define CLK_INFRA_DEVAPC_CK		9
#define CLK_INFRA_AUDIO_CK		10
#define CLK_INFRA_MFG_BUS_CK		11
#define CLK_INFRA_SMI_CK		12
#define CLK_INFRA_DBGCLK_CK		13
#define CLK_INFRA_MD2AHB_CK		14
#define CLK_INFRA_MD2WMIX_CK		15
#define CLK_INFRA_MD2MCU_CK		16
#define CLK_INFRA_MD1AHB_CK		17
#define CLK_INFRA_MD1WMIX_CK		18
#define CLK_INFRA_MD1MCU_CK		19
#define CLK_INFRA_NR_CLK		20

/* CLK_PERI_SYS */

#define CLK_PERI_I2C5_CK		1
#define CLK_PERI_I2C4_CK		2
#define CLK_PERI_I2C3_CK		3
#define CLK_PERI_I2C2_CK		4
#define CLK_PERI_I2C1_CK		5
#define CLK_PERI_I2C0_CK		6
#define CLK_PERI_UART3_CK		7
#define CLK_PERI_UART2_CK		8
#define CLK_PERI_UART1_CK		9
#define CLK_PERI_UART0_CK		10
#define CLK_PERI_IRDA_CK		11
#define CLK_PERI_NLI_CK			12
#define CLK_PERI_MD_HIF_CK		13
#define CLK_PERI_AP_HIF_CK		14
#define CLK_PERI_MSDC30_3_CK		15
#define CLK_PERI_MSDC30_2_CK		16
#define CLK_PERI_MSDC30_1_CK		17
#define CLK_PERI_MSDC20_2_CK		18
#define CLK_PERI_MSDC20_1_CK		19
#define CLK_PERI_AP_DMA_CK		20
#define CLK_PERI_USB1_CK		21
#define CLK_PERI_USB0_CK		22
#define CLK_PERI_PWM_CK			23
#define CLK_PERI_PWM7_CK		24
#define CLK_PERI_PWM6_CK		25
#define CLK_PERI_PWM5_CK		26
#define CLK_PERI_PWM4_CK		27
#define CLK_PERI_PWM3_CK		28
#define CLK_PERI_PWM2_CK		29
#define CLK_PERI_PWM1_CK		30
#define CLK_PERI_THERM_CK		31
#define CLK_PERI_NFI_CK			32
#define CLK_PERI_FHCTL_CK		33
#define CLK_PERI_SPI1_CK		34
#define CLK_PERI_AUXADC_CK		35
#define CLK_PERI_CLK_PERI_PWRAP_CK	36
#define CLK_PERI_I2C6_CK		37
#define CLK_PERI_UART0_SEL		38
#define CLK_PERI_UART1_SEL		39
#define CLK_PERI_UART2_SEL		40
#define CLK_PERI_UART3_SEL		41
#define CLK_PERI_NR_CLK			42

#endif /* _DT_BINDINGS_CLK_MT6589_H */
